import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const usagePageStyles = readFileSync(new URL('./UsagePage.module.scss', import.meta.url), 'utf8')
const usagePageSource = readFileSync(new URL('./UsagePage.tsx', import.meta.url), 'utf8')
const requestEventsSource = readFileSync(new URL('../components/usage/RequestEventsDetailsCard.tsx', import.meta.url), 'utf8')
const priceSettingsSource = readFileSync(new URL('../components/usage/PriceSettingsCard.tsx', import.meta.url), 'utf8')
const chartLineSelectorSource = readFileSync(new URL('../components/usage/ChartLineSelector.tsx', import.meta.url), 'utf8')
const selectSource = readFileSync(new URL('../components/ui/Select.tsx', import.meta.url), 'utf8')
const apiIndexSource = readFileSync(new URL('../components/usage/index.ts', import.meta.url), 'utf8')
const apiClientSource = readFileSync(new URL('../lib/api.ts', import.meta.url), 'utf8')
const i18nSource = readFileSync(new URL('../i18n/index.ts', import.meta.url), 'utf8')
const analysisPanelSource = readFileSync(new URL('../components/usage/analysis/AnalysisPanel.tsx', import.meta.url), 'utf8')
const analysisPanelStyles = readFileSync(new URL('../components/usage/analysis/AnalysisPanel.module.scss', import.meta.url), 'utf8')
const usageChartSource = readFileSync(new URL('../components/usage/UsageChart.tsx', import.meta.url), 'utf8')
const tokenBreakdownChartSource = readFileSync(new URL('../components/usage/TokenBreakdownChart.tsx', import.meta.url), 'utf8')
const costTrendChartSource = readFileSync(new URL('../components/usage/CostTrendChart.tsx', import.meta.url), 'utf8')

describe('UsagePage toolbar styles', () => {
  it('keeps visible range controls content-sized in narrow layouts', () => {
    expect(usagePageStyles).toMatch(/\.timeRangeGroup\s*\{[\s\S]*?width:\s*fit-content;/)
    expect(usagePageStyles).toMatch(/\.timeRangeSelectControl\s*\{[\s\S]*?flex:\s*0 0 164px;/)
  })

  it('keeps refresh controls outside the query filter layout', () => {
    expect(usagePageSource).toContain('{showRangeControls && (\n                  <div className={styles.usageFilterBar}>')
    expect(usagePageSource).toContain('className={styles.usageRefreshSlot}')
    expect(usagePageSource).not.toContain('styles.usageFilterBarCollapsed')
    expect(usagePageStyles).toMatch(/\.usageRefreshSlot\s*\{[\s\S]*?flex:\s*0 0 auto;/)
  })

  it('keeps the API Key filter visible on the Analysis page so Analysis requests can be filtered', () => {
    expect(usagePageSource).not.toContain('shouldShowApiKeyFilter(activeTab)')
    expect(usagePageSource).not.toContain('styles.apiKeyFilterGroupHidden')
    expect(usagePageSource).not.toContain('aria-hidden={!showApiKeyFilter}')
    expect(usagePageStyles).not.toContain('.apiKeyFilterGroupHidden')
  })

  it('uses the new Analysis panel and endpoint instead of the old detail tables', () => {
    expect(usagePageSource).toContain('fetchAnalysis')
    expect(usagePageSource).toContain('<AnalysisPanel')
    expect(usagePageSource).not.toContain('fetchUsageAnalysis')
    expect(usagePageSource).not.toContain('<ApiDetailsCard')
    expect(usagePageSource).not.toContain('<ModelStatsCard')
    expect(apiIndexSource).not.toContain('ApiDetailsCard')
    expect(apiIndexSource).not.toContain('ModelStatsCard')
    expect(apiClientSource).toContain("apiPath('/usage/analysis')")
  })

  it('renames the Analysis tab label and places it before Request Events', () => {
    expect(i18nSource).toContain("tab_analysis: 'Analysis'")
    expect(i18nSource).not.toContain("tab_analysis: 'API & Models'")
    expect(i18nSource).not.toContain("tab_analysis: 'API 与模型'")
    expect(i18nSource).not.toContain("tab_analysis: 'API 與模型'")
    expect(usagePageSource).toContain("const USAGE_TAB_OPTIONS = ['overview', 'analysis', 'events', 'credentials', 'settings'] as const")
  })

  it('keeps mobile tab labels on one line without changing desktop tab sizing', () => {
    const desktopTabPillBlock = usagePageStyles.slice(
      usagePageStyles.indexOf('.tabPill {'),
      usagePageStyles.indexOf('.tabPillActive')
    )

    expect(usagePageStyles).toContain('@include mobile {\n  .tabPill {\n    white-space: nowrap;\n  }\n')
    expect(desktopTabPillBlock).not.toContain('white-space: nowrap;')
  })

  it('lets mobile API Key Settings content scroll inside the card instead of being clipped', () => {
    expect(usagePageStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.apiKeySettingsCard:global\(\.card\)\s*\{[\s\S]*?height:\s*auto;/)
    expect(usagePageStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.apiKeySettingsBody\s*\{[\s\S]*?height:\s*480px;/)
    expect(usagePageStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.apiKeySettingsBody\s*\{[\s\S]*?overflow-y:\s*auto;/)
    expect(usagePageStyles).toMatch(/@include mobile\s*\{[\s\S]*?\.apiKeySettingsList\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\);/)
  })

  it('keeps the Analysis chart presentation aligned with the reference design', () => {
    expect(analysisPanelSource).toContain("t('usage_stats.analysis_token_usage_title')")
    expect(analysisPanelSource).toContain("t('usage_stats.analysis_token_usage_subtitle')")
    expect(analysisPanelSource).toContain("t('usage_stats.analysis_api_key_composition_title')")
    expect(analysisPanelSource).toContain("t('usage_stats.analysis_model_composition_title')")
    expect(analysisPanelSource).toContain("t('usage_stats.analysis_composition_subtitle')")
    expect(analysisPanelSource).toContain("t('usage_stats.analysis_heatmap_title')")
    expect(analysisPanelSource).toContain("t('usage_stats.analysis_heatmap_subtitle')")
    expect(analysisPanelSource).toContain("t('usage_stats.analysis_heatmap_api_key')")
    expect(analysisPanelSource).toContain("t('usage_stats.analysis_heatmap_low')")
    expect(analysisPanelSource).toContain("t('usage_stats.analysis_heatmap_high')")
    expect(analysisPanelSource).toContain("t('usage_stats.analysis_heatmap_cell_title', {")
    expect(analysisPanelSource).toContain("t('usage_stats.input_tokens')")
    expect(analysisPanelSource).toContain("t('usage_stats.output_tokens')")
    expect(analysisPanelSource).toContain("t('usage_stats.cached_tokens')")
    expect(analysisPanelSource).toContain("t('usage_stats.reasoning_tokens')")
    expect(analysisPanelSource).toContain("t('usage_stats.requests_count')")
    expect(analysisPanelSource).not.toContain('<h2>Token Usage Over Time</h2>')
    expect(analysisPanelSource).not.toContain('Input, output, cached and reasoning tokens with request trend.')
    expect(analysisPanelSource).not.toContain('Top usage share by total tokens.')
    expect(analysisPanelSource).not.toContain('<h2>API Key & Models Heatmap</h2>')
    expect(analysisPanelSource).not.toContain('Token distribution across API keys and models.')
    expect(analysisPanelSource).toContain("'#1d4ed8'")
    expect(analysisPanelSource).toContain("'#60a5fa'")
    expect(analysisPanelSource).toContain("'#15803d'")
    expect(analysisPanelSource).toContain("'#22c55e'")
    expect(analysisPanelSource).toContain("'#ca8a04'")
    expect(analysisPanelSource).toContain("'#facc15'")
    expect(analysisPanelSource).toContain("'#7e22ce'")
    expect(analysisPanelSource).toContain("'#c084fc'")
    expect(analysisPanelSource).toContain("'#b91c1c'")
    expect(analysisPanelSource).toContain("'#ef4444'")
    expect(analysisPanelSource).not.toContain("'#a5f1bf'")
    expect(analysisPanelSource).not.toContain("'#f6c183'")
    expect(analysisPanelSource).not.toContain("'#c7bae9'")
    expect(analysisPanelSource).not.toContain("'#7da3f4'")
    expect(analysisPanelSource).toContain("requests: '#ff5a40'")
    expect(analysisPanelSource).not.toContain("'#3AA394'")
    expect(analysisPanelSource).not.toContain("'#4FB06D'")
    expect(analysisPanelSource).not.toContain("'#D6923D'")
    expect(analysisPanelSource).not.toContain("'#8A6BD9'")
    expect(analysisPanelSource).not.toContain("'#B66F3D'")
    expect(analysisPanelSource).not.toContain("'#7ECE84'")
    expect(analysisPanelSource).not.toContain("'#70AFE7'")
    expect(analysisPanelSource).not.toContain("'#AA71EF'")
    expect(analysisPanelSource).not.toContain("'#E9905E'")
    expect(analysisPanelSource).not.toContain("'#EF4E44'")
    expect(analysisPanelSource).not.toContain("'#8B8680'")
    expect(analysisPanelSource).not.toContain("'#2f8f89'")
    expect(analysisPanelSource).not.toContain("'#4f8fd8'")
    expect(analysisPanelSource).not.toContain("'#d9a24a'")
    expect(analysisPanelSource).not.toContain("'#d76f58'")
    expect(analysisPanelSource).not.toContain("'#8abcbc'")
    expect(analysisPanelSource).not.toContain("'#d8655d'")
    expect(analysisPanelSource).not.toContain("'#109890'")
    expect(analysisPanelSource).not.toContain("'#3080f0'")
    expect(analysisPanelSource).not.toContain("'#f0b030'")
    expect(analysisPanelSource).not.toContain("'#f86030'")
    expect(analysisPanelSource).not.toContain("'#80c0c0'")
    expect(analysisPanelSource).toContain('borderDash: [6, 4]')
    expect(analysisPanelSource).not.toContain("'#3f6fe8'")
    expect(analysisPanelSource).not.toContain("'#42c775'")
    expect(analysisPanelSource).not.toContain("'#dd8734'")
    expect(analysisPanelSource).not.toContain("'#8f6bd8'")
    expect(analysisPanelSource).not.toContain("'#d9e6ff'")
    expect(analysisPanelSource).not.toContain("'#d9fbe4'")
    expect(analysisPanelSource).not.toContain("'#ffe0ad'")
    expect(analysisPanelSource).not.toContain("'#e2d6fa'")
    expect(analysisPanelSource).not.toContain("'#8b8680'")
    expect(analysisPanelSource).not.toContain("'#9b7a5c'")
    expect(analysisPanelSource).not.toContain("'#b28b67'")
    expect(analysisPanelSource).not.toContain("'#7f756b'")
    expect(analysisPanelSource).toContain("import { Bar, Doughnut } from 'react-chartjs-2'")
    expect(analysisPanelSource).toContain("import type { ChartData, ChartOptions, Plugin } from 'chart.js'")
    expect(analysisPanelSource).not.toContain("from 'recharts'")
    expect(analysisPanelSource).toContain('buildAnalysisTokenChartOptions')
    expect(analysisPanelSource).toContain('buildTokenLegendItems')
    expect(analysisPanelSource).toContain('maxTicksLimit: 5')
    expect(analysisPanelSource).toContain('maxTicksLimit: 4')
    expect(analysisPanelSource).toContain('buildCompositionChartData')
    expect(analysisPanelSource).toContain('createChartGradient')
    expect(analysisPanelSource).toContain('toGradientFill')
    expect(analysisPanelSource).toContain('ctx.createLinearGradient')
    expect(analysisPanelSource).toContain('gradient.addColorStop(0, color.light)')
    expect(analysisPanelSource).toContain('gradient.addColorStop(1, color.base)')
    expect(analysisPanelSource).toMatch(/input:\s*\{ base:\s*'#2563eb',\s*light:\s*'#93c5fd' \}/)
    expect(analysisPanelSource).toMatch(/output:\s*\{ base:\s*'#16a34a',\s*light:\s*'#86efac' \}/)
    expect(analysisPanelSource).toMatch(/cached:\s*\{ base:\s*'#d97706',\s*light:\s*'#fde68a' \}/)
    expect(analysisPanelSource).toMatch(/reasoning:\s*\{ base:\s*'#8b5cf6',\s*light:\s*'#d8b4fe' \}/)
    expect(analysisPanelSource).toContain('backgroundColor: (context) => toGradientFill(context, tokenColors.input)')
    expect(analysisPanelSource).toContain('backgroundColor: (context) => toGradientFill(context, CHART_COLORS[context.dataIndex % CHART_COLORS.length])')
    expect(analysisPanelSource).toContain('<Bar data={chartData} options={chartOptions} plugins={[drawRequestsLineOnTopPlugin]} />')
    expect(analysisPanelSource).toContain('const drawRequestsLineOnTopPlugin')
    expect(analysisPanelSource).toContain('meta.type === \'line\'')
    expect(analysisPanelSource).toContain('<Doughnut data={chartData} options={chartOptions} />')
    expect(analysisPanelSource).toContain('formatPercent')
    expect(analysisPanelSource).toContain('toFixed(2)')
    expect(analysisPanelSource).not.toContain('API Key × Model Heatmap')
    expect(analysisPanelSource).not.toContain('<span>{formatCompactNumber(toNumber(cell?.total_tokens))}</span>')
    expect(analysisPanelSource).not.toContain('<small>{formatCompactNumber(toNumber(cell?.requests))} req</small>')
    expect(analysisPanelSource).not.toContain('<span>Low</span>')
    expect(analysisPanelSource).not.toContain('<span>High</span>')
    expect(analysisPanelSource).toContain('heatmapLegend')
    expect(analysisPanelSource).toContain('getHeatmapCellGradient')
    expect(analysisPanelSource).toContain('linear-gradient(180deg')
    expect(analysisPanelSource).toContain('chartTheme')
    expect(analysisPanelSource).toContain("requests: '#ff5a40'")
    expect(analysisPanelSource).not.toContain('requests: chartTheme.textPrimary')
    expect(analysisPanelSource).not.toContain("requests: '#111827'")
    expect(analysisPanelSource).toContain('className={styles.analysisChartSurface}')
    expect(analysisPanelSource).toContain('className={styles.analysisChartLegend}')
    expect(analysisPanelSource).toContain('className={styles.analysisLegendItem}')
    expect(analysisPanelSource).toContain('className={styles.analysisLegendDot}')
    expect(analysisPanelSource).toContain('className={styles.analysisLegendLabel}')
    expect(analysisPanelSource).toContain('legend: { display: false }')
    expect(analysisPanelSource).toContain('tooltip: {')
    expect(analysisPanelSource).toContain('ticks: { color: chartTheme.textSecondary')
    expect(analysisPanelSource).toContain('gridTemplateColumns: `150px repeat(${models.length}, minmax(75px, 1fr))`')
    expect(analysisPanelSource).toContain('className={`${styles.heatmapHeaderCell} ${styles.heatmapTooltipTarget}`}')
    expect(analysisPanelSource).toContain('className={`${styles.heatmapRowLabel} ${styles.heatmapTooltipTarget}`}')
    expect(analysisPanelSource).toContain('className={styles.heatmapTruncatedLabel}')
    expect(analysisPanelSource).toContain('data-full-name={model}')
    expect(analysisPanelSource).toContain('data-full-name={apiKey}')
    expect(analysisPanelSource).toContain('background: getHeatmapCellGradient(intensity)')
    expect(analysisPanelSource).toContain('interpolateColor([255, 250, 238], [226, 181, 98]')
    expect(analysisPanelSource).toContain('interpolateColor([214, 162, 76], [198, 87, 70]')
    expect(analysisPanelStyles).toMatch(/\.analysisChartSurface\s*\{[\s\S]*?background:\s*var\(--bg-secondary\);/)
    expect(analysisPanelStyles).toMatch(/\.analysisChartSurface\s*\{[\s\S]*?border:\s*1px solid var\(--border-color\);/)
    expect(analysisPanelStyles).toMatch(/\.analysisChartLegend\s*\{[\s\S]*?display:\s*flex;/)
    expect(analysisPanelStyles).toMatch(/\.analysisLegendItem\s*\{[\s\S]*?font-size:\s*12px;/)
    expect(analysisPanelStyles).toMatch(/\.analysisLegendDot\s*\{[\s\S]*?width:\s*10px;/)
    expect(analysisPanelStyles).toMatch(/\.heatmapGrid\s*\{[\s\S]*?width:\s*100%;/)
    expect(analysisPanelStyles).toMatch(/\.heatmapGrid\s*\{[\s\S]*?min-width:\s*0;/)
    expect(analysisPanelStyles).not.toContain('min-width: max-content')
    expect(analysisPanelStyles).toMatch(/\.heatmapTooltipTarget\s*\{[\s\S]*?position:\s*relative;/)
    expect(analysisPanelStyles).toMatch(/\.heatmapTooltipTarget\s*\{[\s\S]*?overflow:\s*visible;/)
    expect(analysisPanelStyles).toMatch(/\.heatmapTruncatedLabel\s*\{[\s\S]*?text-overflow:\s*ellipsis;/)
    expect(analysisPanelStyles).toMatch(/\.heatmapTooltipTarget:hover::after\s*\{[\s\S]*?content:\s*attr\(data-full-name\);/)
    expect(analysisPanelStyles).toMatch(/\.heatmapCell\s*\{[\s\S]*?height:\s*24px;/)
    expect(analysisPanelStyles).toMatch(/\.heatmapCell\s*\{[\s\S]*?border-radius:\s*4px;/)
    expect(analysisPanelStyles).not.toMatch(/\.heatmapCell\s*\{[^}]*linear-gradient/)
    expect(analysisPanelStyles).toMatch(/\.heatmapRowLabel\s*\{[\s\S]*?border:\s*0;/)
    expect(analysisPanelStyles).toMatch(/\.heatmapLegend\s*\{[\s\S]*?justify-content:\s*center;/)
    expect(analysisPanelStyles).toMatch(/\.heatmapLegend\s*\{[\s\S]*?padding-top:\s*28px;/)
    expect(analysisPanelStyles).toMatch(/\.heatmapLegendRamp\s*\{[\s\S]*?linear-gradient\(90deg, rgb\(250, 244, 230\), rgb\(214, 162, 76\), rgb\(198, 87, 70\)\)/)
    expect(analysisPanelStyles).toMatch(/\.compositionGrid\s*\{[\s\S]*?@include tablet\s*\{[\s\S]*?grid-template-columns:\s*1fr;/)
    expect(analysisPanelStyles).toMatch(/\.compositionGrid\s*\{[\s\S]*?@include mobile\s*\{[\s\S]*?grid-template-columns:\s*1fr;/)
    expect(analysisPanelStyles).not.toContain('recharts-legend')
    expect(analysisPanelSource).not.toContain('<BarChart')
    expect(analysisPanelSource).toContain('font: { size: 10 }')
  })

  it('widens only the API key dropdown menu without changing the trigger width', () => {
    expect(selectSource).toContain('dropdownMinWidth?: number')
    expect(selectSource).toContain('rect.left - (width - rect.width) / 2')
    expect(usagePageSource).toContain('dropdownMinWidth={180}')
  })

  it('preserves the original desktop toolbar sizing while isolating refresh layout', () => {
    expect(usagePageStyles).toMatch(/\.toolbarActionsRight\s*\{[\s\S]*?align-items:\s*center;/)
    expect(usagePageStyles).toMatch(/\.usageFilterBar\s*\{[\s\S]*?align-items:\s*center;/)
    expect(usagePageStyles).toMatch(/\.usageFilterBar\s*\{[\s\S]*?flex:\s*1 1 auto;/)
    expect(usagePageStyles).toMatch(/\.apiKeySelectControl\s*\{[\s\S]*?width:\s*172px;/)
    expect(usagePageStyles).toMatch(/\.apiKeySelectControl\s*\{[\s\S]*?flex:\s*0 0 172px;/)
    expect(usagePageStyles).toMatch(/\.rangeSelectControl\s*\{[\s\S]*?width:\s*164px;/)
    expect(usagePageStyles).toMatch(/\.rangeSelectControl\s*\{[\s\S]*?flex:\s*0 0 164px;/)
  })

  it('keeps custom range inputs hidden and disabled until the custom range is selected', () => {
    expect(usagePageSource).toContain('styles.customRangeFieldGroupOpen')
    expect(usagePageSource).toContain('aria-hidden={!isCustomRange}')
    expect(usagePageSource).toContain('disabled={!isCustomRange}')
    expect(usagePageSource).not.toContain('{isCustomRange && (')
  })

  it('keeps custom date inputs selectable through the native picker without pointer interception', () => {
    expect(usagePageStyles).toMatch(/\.customRangeInput\s*\{[\s\S]*?user-select:\s*none;/)
    expect(usagePageStyles).toMatch(/\.customRangeInput\s*\{[\s\S]*?-webkit-user-select:\s*none;/)
    expect(usagePageSource).not.toContain('readOnly')
    expect(usagePageSource).not.toContain('onPointerDown={handleCustomDateInputPointerDown}')
    expect(usagePageSource).toContain('onClick={handleCustomDateInputActivate}')
    expect(usagePageSource).toContain('onFocus={handleCustomDateInputActivate}')
    expect(usagePageSource).toContain('onKeyDown={handleCustomDateInputKeyDown}')
  })

  it('keeps Overview chart period controls hidden because period selection is automatic', () => {
    expect(usageChartSource).not.toContain('className={styles.periodButtons}')
    expect(tokenBreakdownChartSource).not.toContain('className={styles.periodButtons}')
    expect(costTrendChartSource).not.toContain('className={styles.periodButtons}')
  })

  it('places Chart Line Selection and trend cards below Cost Trend on Overview', () => {
    const serviceHealthIndex = usagePageSource.indexOf('<ServiceHealthCard')
    const tokenBreakdownIndex = usagePageSource.indexOf('<TokenBreakdownChart')
    const costTrendIndex = usagePageSource.indexOf('<CostTrendChart')
    const chartLineSelectorIndex = usagePageSource.indexOf('<ChartLineSelector')
    const chartsGridIndex = usagePageSource.indexOf('<div className={styles.chartsGrid}>')

    expect(serviceHealthIndex).toBeGreaterThan(-1)
    expect(tokenBreakdownIndex).toBeGreaterThan(serviceHealthIndex)
    expect(costTrendIndex).toBeGreaterThan(tokenBreakdownIndex)
    expect(chartLineSelectorIndex).toBeGreaterThan(costTrendIndex)
    expect(chartsGridIndex).toBeGreaterThan(chartLineSelectorIndex)
  })

  it('keeps chart line controls aligned with reusable pill controls', () => {
    expect(chartLineSelectorSource).toContain('className={styles.usagePillControl}')
    expect(chartLineSelectorSource).toContain('className={styles.usagePillAction}')
  })

  it('aligns Request Event Log pagination with credential pagination height', () => {
    expect(usagePageStyles).toMatch(/\.requestEventsCard:global\(\.card\)\s*\{[\s\S]*?padding-bottom:\s*0;/)
    expect(requestEventsSource).toContain('className={styles.requestEventsCard}')
    expect(usagePageStyles).toMatch(/\.requestEventsPaginationFooter\s*\{[\s\S]*?--usage-pagination-bar-height:\s*51px;/)
    expect(usagePageStyles).toMatch(/\.requestEventsPaginationFooter\s*\{[\s\S]*?height:\s*var\(--usage-pagination-bar-height\);/)
    expect(usagePageStyles).toMatch(/\.requestEventsPaginationFooter\s*\{[\s\S]*?box-sizing:\s*border-box;/)
    expect(usagePageStyles).toMatch(/\.requestEventsPaginationFooter\s*\{[\s\S]*?align-items:\s*center;/)
    expect(usagePageStyles).toMatch(/\.requestEventsPaginationFooter\s*\{[\s\S]*?padding:\s*0 #\{\$spacing-lg\};/)
  })

  it('keeps Request Event Log headers visible while the table scrolls', () => {
    expect(usagePageStyles).toMatch(/\.requestEventsTableWrapper\s*\{[\s\S]*?height:\s*clamp\(400px,\s*60vh,\s*600px\);/)
    expect(usagePageStyles).toMatch(/\.requestEventsTableWrapper\s*\{[\s\S]*?overflow:\s*auto;/)
    expect(usagePageStyles).toMatch(/\.requestEventsTableWrapper\s*\{[\s\S]*?thead\s+th\s*\{[\s\S]*?position:\s*sticky;/)
    expect(usagePageStyles).toMatch(/\.requestEventsTableWrapper\s*\{[\s\S]*?thead\s+th\s*\{[\s\S]*?top:\s*0;/)
    expect(usagePageStyles).toMatch(/\.requestEventsTableWrapper\s*\{[\s\S]*?thead\s+th\s*\{[\s\S]*?z-index:\s*2;/)
    expect(usagePageStyles).toMatch(/\.requestEventsTableWrapper\s*\{[\s\S]*?\.table\s*\{[\s\S]*?border-collapse:\s*separate;/)
  })

  it('keeps the Request Event Log timestamp column compact', () => {
    expect(usagePageStyles).toMatch(/\.requestEventsTimestamp\s*\{[\s\S]*?width:\s*136px;/)
    expect(usagePageStyles).toMatch(/\.requestEventsTimestamp\s*\{[\s\S]*?min-width:\s*136px;/)
    expect(usagePageStyles).toMatch(/\.requestEventsTimestamp\s*\{[\s\S]*?font-variant-numeric:\s*tabular-nums;/)
  })

  it('keeps the Request Event Log reasoning header on one line without fixing column width', () => {
    expect(usagePageStyles).toMatch(/\.requestEventsReasoningHeader\s*\{[\s\S]*?white-space:\s*nowrap;/)
    expect(usagePageStyles).not.toMatch(/\.requestEventsReasoningHeader\s*\{[^}]*width:/)
    expect(requestEventsSource).toContain('<th className={styles.requestEventsReasoningHeader}>{t(\'usage_stats.reasoning_tokens\')}</th>')
  })

  it('provides reusable pill controls for usage subpages', () => {
    expect(usagePageStyles).toMatch(/\.usagePillControl\s*\{[\s\S]*?border-radius:\s*999px;/)
    expect(usagePageStyles).toMatch(/\.usagePillAction\s*\{[\s\S]*?border-radius:\s*999px;/)
    expect(usagePageStyles).toMatch(/\.usagePillActionDanger\s*\{[\s\S]*?color:/)
    expect(usagePageStyles).not.toContain('&:global(.btn-danger):hover:not(:disabled)')
    expect(usagePageStyles).toMatch(/:global\(\.input\)\s*\{[^}]*border-radius:\s*999px;/)
    expect(requestEventsSource).toContain('styles.usagePillControl')
    expect(requestEventsSource).toContain('styles.usagePillAction')
    expect(priceSettingsSource).toContain('styles.usagePillControl')
    expect(priceSettingsSource).toContain('styles.usagePillAction')
    expect(priceSettingsSource).toContain('styles.usagePillActionDanger')
  })
})
